services:
  - type: web
    name: phoenix
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: TMDB_API_KEY
        sync: false
      - key: FLARESOLVERR_ENDPOINT
        value: https://phoenix-flaresolverr.onrender.com
      - key: ALL_PROXY
        sync: false
